-- Category Table
CREATE TABLE CATAGORY_DETAILS (
    CATEGORYID VARCHAR2(20) PRIMARY KEY,
    CATEGORYNAME VARCHAR2(30) NOT NULL
);

-- Product Table
CREATE TABLE PRODUCT_DETAILS (
    PRODUCTID VARCHAR2(20) PRIMARY KEY,
    PRODUCTNAME VARCHAR2(20) NOT NULL,
    PRODUCTPRICE NUMBER(10, 2) NOT NULL,
    COMPANTEMAIL VARCHAR2(255) UNIQUE NOT NULL,
    CATEGORIEID VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_CATEGORY
        FOREIGN KEY (CATEGORIEID)
        REFERENCES CATAGORY_DETAILS(CATEGORYID)
);
